apiVersion: batch/v1
kind: CronJob
metadata:
  name: ioc-loader
spec:
  # kubectl create job --from=cronjob/ioc-loader ioc-loader-001 -n pp-production
  suspend: false
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
          - name: cron-script
            image: "pjamenaja/please-protect-jobs:{{ .Values.ppJob.imageTag }}"
            imagePullPolicy: IfNotPresent
            command:
            - ruby
            args:
            - /scripts/ioc-loader.rb
            env:
            - name: ENVIRONMENT 
              value: {{ .Values.envAliasJob }}

            - name: REDIS_HOST
              value: "redis-master.redis.svc.cluster.local"

            - name: REDIS_PORT
              value: "6379"

            - name: PG_HOST
              value: postgresql.postgresql-{{ .Values.envGroup }}.svc.cluster.local

            - name: PG_PORT
              value: "5432"

            - name: PG_USER
              value: "postgres"

            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pp-postgres-secret
                  key: adminPasswordKey
                  optional: false

            - name: PG_DB
              value: "pp-{{ .Values.envGroup }}"

            - name: TEMP_DIR
              value: '/data/temp'

            - name: REDIS_HOST
              value: "redis-master.redis.svc.cluster.local"

            - name: REDIS_PORT
              value: "6379"

            volumeMounts:
            - name: temp-dir
              mountPath: /data/temp

          restartPolicy: OnFailure

          volumes:
          - name: temp-dir
            emptyDir: {}
