apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-dispatcher
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: job-dispatcher
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: job-dispatcher
    spec:
      serviceAccountName: pp-sa
      containers:
      - env:
        - name: ENVIRONMENT 
          value: {{ .Values.envAliasJob }}

        - name: TZ
          value: "Asia/Bangkok"

        - name: REDIS_HOST
          value: "redis-master.redis.svc.cluster.local"

        - name: REDIS_PORT
          value: "6379"

        - name: PG_HOST
          value: postgresql.postgresql-{{ .Values.envGroup }}.svc.cluster.local

        - name: PG_PORT
          value: "5432"

        - name: PG_USER
          value: "postgres"

        - name: PG_DB
          value: pp-{{ .Values.envGroup }}

        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pp-postgres-secret
              key: adminPasswordKey
              optional: false

        - name: TEMP_DIR
          value: '/data/temp'

        command:
          - ruby
        args:
          - /scripts/job-dispatcher.rb
        image: "pjamenaja/please-protect-jobs:{{ .Values.ppJob.imageTag }}"
        imagePullPolicy: Always
        
        name: job-dispatcher
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi

        volumeMounts:
        - name: temp-dir
          mountPath: /data/temp

      volumes:
      - emptyDir: {}
        name: temp-dir
